name: Auto-add Bug Issues to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: read
  contents: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check for bug label and add to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue?.number || context.payload.pull_request?.number;
            const isIssue = !!context.payload.issue;
            
            if (!issueNumber) return;
            
            // Get the issue/PR details to check labels
            const { data: item } = await github.rest.issues.get({
              owner,
              repo,
              issue_number: issueNumber
            });
            
            // Check if it has a bug label
            const hasBugLabel = item.labels.some(label => 
              label.name.toLowerCase().includes('bug')
            );
            
            if (!hasBugLabel) {
              console.log(`${isIssue ? 'Issue' : 'PR'} #${issueNumber} does not have a bug label - skipping`);
              return;
            }
            
            console.log(`New ${isIssue ? 'issue' : 'PR'} #${issueNumber} created with bug label - adding to project`);
            
            // CONFIGURE: Your project name
            const targetProjectName = 'Test Project';
            
            // Get issue/PR ID and find the project
            const query = `
              query($owner: String!, $repo: String!, $issueNumber: Int!, $login: String!) {
                repository(owner: $owner, name: $repo) {
                  ${isIssue ? 'issue' : 'pullRequest'}(number: $issueNumber) {
                    id
                  }
                }
                user(login: $login) {
                  projectsV2(first: 10, query: "Test") {
                    nodes {
                      id
                      title
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue {
                              id
                              number
                            }
                            ... on PullRequest {
                              id
                              number
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            const result = await github.graphql(query, {
              owner,
              repo,
              issueNumber,
              login: 'williampln' // Your personal GitHub username
            });
            
            const itemId = result.repository[isIssue ? 'issue' : 'pullRequest'].id;
            console.log(`${isIssue ? 'Issue' : 'PR'} ID: ${itemId}`);
            
            // Find the target project in user's personal projects
            const targetProject = result.user.projectsV2.nodes.find(
              project => project.title === targetProjectName
            );
            
            if (!targetProject) {
              console.log(`Personal project "${targetProjectName}" not found`);
              console.log('Available personal projects:', result.user.projectsV2.nodes.map(p => p.title));
              return;
            }
            
            console.log(`Found target project: ${targetProject.title}`);
            
            // Check if item is already in the project
            const existingItem = targetProject.items.nodes.find(item => 
              item.content && item.content.id === itemId
            );
            
            if (existingItem) {
              console.log(`${isIssue ? 'Issue' : 'PR'} #${issueNumber} is already in project "${targetProjectName}"`);
              return;
            }
            
            // Add the item to the project
            const addMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemByContentId(input: {
                  projectId: $projectId
                  contentId: $contentId
                }) {
                  item {
                    id
                  }
                }
              }
            `;
            
            await github.graphql(addMutation, {
              projectId: targetProject.id,
              contentId: itemId
            });
            
            console.log(`Successfully added ${isIssue ? 'issue' : 'PR'} #${issueNumber} to project "${targetProjectName}"`);
