name: Sync Priority Field with Labels

on:
  issues:
    types: [labeled, unlabeled, opened, edited]
  pull_request:
    types: [labeled, unlabeled, opened, edited]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Specific issue number to sync (leave empty to sync all open issues with priority labels)'
        required: false
        type: string

jobs:
  sync-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Priority Field
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue?.number || context.payload.pull_request?.number;
            
            if (!issueNumber) return;
            
            // Get the issue/PR details
            const { data: issue } = await github.rest.issues.get({
              owner,
              repo,
              issue_number: issueNumber
            });
            
            // Define priority mapping - UPDATE THESE TO MATCH YOUR EXACT LABEL NAMES
            const priorityLabels = {
              'Highest': 'Highest',  // Change left side to your exact label name
              'High': 'High',        // Change left side to your exact label name
              'Medium': 'Medium',    // Change left side to your exact label name
              'Low': 'Low'           // Change left side to your exact label name
            };
            
            // Find the highest priority label
            let priority = null;
            const labelNames = issue.labels.map(label => label.name);
            console.log(`Issue #${issueNumber} labels:`, labelNames);
            
            for (const [label, priorityValue] of Object.entries(priorityLabels)) {
              if (labelNames.includes(label)) {
                priority = priorityValue;
                console.log(`Found priority label: ${label} -> ${priorityValue}`);
                break; // Takes the first match (highest priority)
              }
            }
            
            if (!priority) {
              console.log('No priority labels found');
              return;
            }
            
            // Get project items for this issue - works for user, repo, and org projects
            const issueQuery = `
              query($owner: String!, $repo: String!, $issueNumber: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issueNumber) {
                    id
                    projectItems(first: 50) {
                      nodes {
                        id
                        project {
                          id
                          title
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            // Also search user projects - simplified query
            const userQuery = `
              query($login: String!) {
                user(login: $login) {
                  projectsV2(first: 50) {
                    nodes {
                      id
                      title
                      items(first: 100) {
                        nodes {
                          id
                          content {
                            ... on Issue {
                              id
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            // First get the issue details and repository projects
            const issueResult = await github.graphql(issueQuery, {
              owner,
              repo,
              issueNumber
            });
            
            const issueId = issueResult.repository.issue.id;
            let projectItems = issueResult.repository.issue.projectItems.nodes;
            
            console.log(`Issue ID: ${issueId}`);
            
            // Then search user projects
            try {
              const userResult = await github.graphql(userQuery, {
                login: owner
              });
              
              console.log(`Searching user projects for: ${owner}`);
              console.log(`Found ${userResult.user.projectsV2.nodes.length} user projects`);
              
              // Find user projects that contain this issue
              for (const project of userResult.user.projectsV2.nodes) {
                console.log(`Checking project: ${project.title} (${project.items.nodes.length} items)`);
                
                const matchingItems = project.items.nodes.filter(item => 
                  item.content && item.content.id === issueId
                );
                
                console.log(`Found ${matchingItems.length} matching items in ${project.title}`);
                
                for (const item of matchingItems) {
                  console.log(`Adding project item: ${item.id} from project: ${project.title}`);
                  projectItems.push({
                    id: item.id,
                    project: {
                      id: project.id,
                      title: project.title
                    }
                  });
                }
              }
            } catch (error) {
              console.log(`Error accessing user projects for ${owner}:`, error.message);
            }
            
            // Also try organization projects if the user is part of an org
            try {
              const orgQuery = `
                query($owner: String!) {
                  organization(login: $owner) {
                    projectsV2(first: 50) {
                      nodes {
                        id
                        title
                        items(first: 100) {
                          nodes {
                            id
                            content {
                              ... on Issue {
                                id
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const orgResult = await github.graphql(orgQuery, {
                login: owner
              });
              
              console.log(`Found ${orgResult.organization.projectsV2.nodes.length} organization projects`);
              
              for (const project of orgResult.organization.projectsV2.nodes) {
                console.log(`Checking org project: ${project.title} (${project.items.nodes.length} items)`);
                
                const matchingItems = project.items.nodes.filter(item => 
                  item.content && item.content.id === issueId
                );
                
                for (const item of matchingItems) {
                  projectItems.push({
                    id: item.id,
                    project: {
                      id: project.id,
                      title: project.title
                    }
                  });
                }
              }
            } catch (error) {
              console.log(`${owner} is not an organization or no org projects found`);
            }
            
            console.log(`Found ${projectItems.length} project items for issue #${issueNumber}`);
            console.log('Projects:', projectItems.map(item => item.project.title));
            
            if (projectItems.length === 0) {
              console.log('Issue is not in any projects yet');
              return;
            }
            
            // Update priority field for each project item
            for (const projectItem of projectItems) {
              // Get project fields
              const fieldsQuery = `
                query($projectId: ID!) {
                  node(id: $projectId) {
                    ... on ProjectV2 {
                      fields(first: 20) {
                        nodes {
                          ... on ProjectV2SingleSelectField {
                            id
                            name
                            options {
                              id
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const fieldsResult = await github.graphql(fieldsQuery, {
                projectId: projectItem.project.id
              });
              
              console.log(`Project: ${projectItem.project.title}`);
              console.log('Available fields:', fieldsResult.node.fields.nodes.map(f => f.name));
              
              // Find the Priority field (update this name to match your field)
              const priorityField = fieldsResult.node.fields.nodes.find(
                field => field.name === 'Priority' // Change this to match your exact field name
              );
              
              if (!priorityField) {
                console.log(`Priority field not found in project ${projectItem.project.title}`);
                continue;
              }
              
              console.log('Priority field options:', priorityField.options.map(opt => opt.name));
              
              if (priorityField && priority) {
                // Find the option ID for the priority value
                const option = priorityField.options.find(opt => opt.name === priority);
                
                if (option) {
                  // Update the field
                  const updateMutation = `
                    mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
                      updateProjectV2ItemFieldValue(input: {
                        projectId: $projectId
                        itemId: $itemId
                        fieldId: $fieldId
                        value: $value
                      }) {
                        projectV2Item {
                          id
                        }
                      }
                    }
                  `;
                  
                  await github.graphql(updateMutation, {
                    projectId: projectItem.project.id,
                    itemId: projectItem.id,
                    fieldId: priorityField.id,
                    value: {
                      singleSelectOptionId: option.id
                    }
                  });
                  
                  console.log(`Updated priority to ${priority} for issue #${issueNumber} in project ${projectItem.project.title}`);
                }
              } else if (priorityField && !priority) {
                // Clear the priority field if no priority label exists
                const updateMutation = `
                  mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: ProjectV2FieldValue!) {
                    updateProjectV2ItemFieldValue(input: {
                      projectId: $projectId
                      itemId: $itemId
                      fieldId: $fieldId
                      value: $value
                    }) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `;
                
                await github.graphql(updateMutation, {
                  projectId: projectItem.project.id,
                  itemId: projectItem.id,
                  fieldId: priorityField.id,
                  value: {
                    singleSelectOptionId: null
                  }
                });
                
                console.log(`Cleared priority for issue #${issueNumber} in project ${projectItem.project.title}`);
              }
            }
